### ISSUE TITLE
this doesn't close sqlalchemy connections

### ISSUE THREAD

**Issue by jvanasco** [Pylons/pyramid-cookiecutter-alchemy#32]
referencing via this post: https://groups.google.com/forum/#!topic/pylons-discuss/_MJflNUcjdg

the standard ways to implement sqlalchemy for years has been to add a finished_callback (https://docs.pylonsproject.org/projects/pyramid-cookbook/en/latest/database/sqlalchemy.html) or use a tween to close the dbSession.

maybe i missed something, but this cookiecutter doesn't seem to do either or import anything that does.

**Comment by digitalresistor** [comment]
pyramid_tm closes/cleans up the session when you are done with it using transaction.

**Comment by digitalresistor** [comment]
https://github.com/Pylons/pyramid-cookiecutter-alchemy/blob/latest/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.repo_name%7D%7D/models/__init__.py#L63

For where `pyramid_tm` gets included.

**Comment by jvanasco** [comment]
Sorry.  I see that it calls a _finish() method that eventually gets to a close in zope

https://github.com/zopefoundation/zope.sqlalchemy/blob/master/src/zope/sqlalchemy/datamanager.py#L80-L91
