### ISSUE TITLE
alembic migrations: need to have the [alembic] section in all ini files

### ISSUE THREAD

**Issue by petrblahos** [Pylons/pyramid-cookiecutter-alchemy#36]
I am a bit doubtful about the need to have the `[alembic] section` in all ini files. If I am not mistaken, the `[alembic]script_location` must be same in all config files for migrations to work. Then I think putting it into the config file is sort of confusing and can cause mistakes. What about adding something like this into alembic's `env.py`?

`if not config.get_main_option("script_location"):     config.set_main_option("script_location", "{{ cookiecutter.repo_name }}/alembic")`

Thus, the settings in the ini files would continue working but they would be optional.

If we agree on this, I will prepare a pull request...

**Comment by petrblahos** [comment]
Right, it looks like the code snip above does not work anyway, because alembic expects the script_location key to be present when it loads the config file.

**Comment by stevepiercy** [comment]
Closing as there isn't anything to change after all.
