### ISSUE TITLE
uWSGI Entry Point

### ISSUE THREAD

**Issue by jackdesert** [Pylons/pyramid-cookiecutter-alchemy#40]
Would you be so kind as to provide a working uWSGI entry point for this cookiecutter?
-------------------------------------------------------------------------------------------------------------

There already exist tutorials on setting up uWSGI to serve REALLY BASIC pyramid applications. But their methods don't work with this cookiecutter, because there is not just one single python file that has an "application" defined.

How to Recreate Issue
-----------------------------

Say I create a new application named "umbrella":

    python3 -m cookiecutter gh:Pylons/pyramid-cookiecutter-alchemy

After following the instructions output from the cookiecutter, running `pserve` works fine:

    env/bin/pserve production.ini  # this works fine!

But say now I want to run it from uWSGI like this:

    uwsgi --chmod-socket=020 --enable-threads --plugin=python3 -s /tmp/umbrella.sock --manage-script-name --mount /=wsgi:application

Based on the "--mount /=wsgi:application" part of the invocation, uWSGI expects to have an entry point (python file) by the name of "wsgi.py" that defines a variable named "application". *Would you be so kind as to provide such a wsgi.py file that will work?*

My best effort is the following:

    # wsgi.py
    from umbrella import main
    import pyramid

    global_config = {'__file__': '/home/ubuntu/umbrella/production.ini',
                     'here': '/home/ubuntu/umbrella'}

    settings = {'pyramid.reload_templates': 'false',
                'pyramid.debug_authorization': 'false',
                'pyramid.debug_notfound': 'false',
                'pyramid.debug_routematch': 'false', i
                'pyramid.default_locale_name': 'en',
                'sqlalchemy.url': 'sqlite:////home/ubuntu/umbrella/umbrella.sqlite',
                'retry.attempts': '3'}

    application = main(global_config, settings=settings)

    if __name__ == '__main__':
        # uWSGI won't call this section, but it gives us a way to test the code above
        # using env/bin/python wsgi.py
        from waitress import serve
        serve(application, host='0.0.0.0', port=6542)

But whether it's invoked via the uwsgi incantation shows above or via a simple `env/bin/python wsgi.py`, it gives the same error:

    $ env/bin/python wsgi.py
    Traceback (most recent call last):
      File "wsgi.py", line 15, in <module>
        application = main(global_config, settings=settings)
      File "/home/ubuntu/umbrella/umbrella/__init__.py", line 12, in main
        config.include('.models')
      File "/home/ubuntu/umbrella/env/lib/python3.6/site-packages/pyramid/config/__init__.py", line 839, in include
        c(configurator)
      File "/home/ubuntu/umbrella/umbrella/models/__init__.py", line 69, in includeme
        session_factory = get_session_factory(get_engine(settings))
      File "/home/ubuntu/umbrella/umbrella/models/__init__.py", line 17, in get_engine
        return engine_from_config(settings, prefix)
      File "/home/ubuntu/umbrella/env/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 464, in engine_from_config
        url = options.pop('url')
    KeyError: 'url'

Not saying this is necessarily a bug with the cookiecutter, but hoping you can offer
some advice anyway.

**Comment by stevepiercy** [comment]
@jackdesert please see [General Support](https://pylonsproject.org/community-support.html). Configuration of a uWSGI server or any other server beside the default Waitress is beyond the scope of the cookiecutters. You might find the [Pyramid Community Cookbook](https://docs.pylonsproject.org/projects/pyramid_cookbook/en/latest/deployment/index.html) helpful for your specific WSGI server.

The issue tracker is the last place to turn for support in this case. I'm closing this issue for now. Feel free to reopen if you think this is a bug or can make the case for adding this as a feature request provided you submit a PR with tests.
